language: cpp

matrix:
  include:
# Curl fails on x86_64 travis VMs, someone who knows what they are doing should fix
#    - os: linux
#      compiler: gcc
#      script: cd main/source/linux && make
#      env: OPJ_CI_ARCH=i386
#      addons:
#        apt:
#          packages:
#            - gcc-multilib
#            - g++-multilib
#            - libcurl4-openssl-dev

    - os: osx
      compiler: clang
      before_script:
      - export CC=clang
      - export CPLUS=clang++
      script: cd main/source/linux && make