language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      script: cd main/source/linux && make
      packages:
        - g++-6
        - g++-6-multilib
        - gcc-multilib

    - os: osx
      compiler: clang
      before_script:
      - export CC=clang
      - export CPLUS=clang++
      script: cd main/source/linux && make